### ISSUE TITLE
Notification templates contain wrong link to a resource  record-64.png

### ISSUE THREAD

**Issue by mmrvelj** [Alfresco/records-management#13]
https://github.com/Alfresco/records-management/blob/e86cd3a04a6ab41d68014d91b0676ce1e2628165/rm-community/rm-community-repo/config/alfresco/module/org_alfresco_module_rm/bootstrap/content/notify-records-due-for-review-email.ftl#L85

Following files all have incorrect path to record-64.png resource:

- notify-records-due-for-review-email.ftl
- record-rejected-email.ftl
- record-superseded-email.ftl

Correct link should be:
${shareUrl}/rm/components/documentlibrary/images/record-64.png

**Comment by tpage-alfresco** [comment]
Thank you for raising this issue. We have created a mirror ticket to track it in our JIRA instance: https://issues.alfresco.com/jira/browse/APPS-509

**Comment by tpage-alfresco** [comment]
Fixed by https://github.com/Alfresco/records-management/commit/867623fbe55051dc8507cdaf674c1b5971b27e16
