### ISSUE TITLE
Saved Searches in Records Search not showing message values but keys

### ISSUE THREAD

**Issue by mmrvelj** [Alfresco/records-management#15]
By going to menu "Records Search" and selecting dropdown "Saved Searches", instead of showing values such as "Records and Record Folders Eligible for Cut Off" from *.properties files (e.g. rm-system.properties) we are seeing the message keys, such as "rm.savedsearch.cutoffRecordsName".

**Comment by rodicasutu** [comment]
Fixed on AGS 3.5.a

**Comment by rodicasutu** [comment]
Closing this due as I assume it has been resolved. Please feel free to reopen if you still reproduce it.
