### ISSUE TITLE
Adding only record management to community_share and community_acs alfresco ?

### ISSUE THREAD

**Issue by AdemOch** [Alfresco/records-management#17]
I am trying to add only record management to my customized version of Share and Platform of Alfresco is that possible and how?
PS: I have a containerized installation of Alfresco community.
alfresco platform version 6.1.2-ga
share version is 6.1.0-RC3
apache-maven 3.6.3

**Comment by tpage-alfresco** [comment]
There are a few challenges to do this, but perhaps some of the following information will help you.

Firstly it's worth noting that the most recent version of community AGS is 3.0.a from 2018.  The release blog post for it is here: https://hub.alfresco.com/t5/alfresco-content-services-blog/alfresco-governance-services-3-0/ba-p/288275  We tested this against ACS 6.0, not 6.1, so I expect you will run into issues in your environment.

Alternatively, if you're happy to build AGS from the source then you might be able to build a more recent version of Community AGS to use.  Enterprise AGS 3.1 is compatible with ACS 6.1, and Enterprise AGS 3.2, 3.3 and 3.4 are compatible with ACS 6.2. There is a thread here asking when a new release will come out: https://github.com/Alfresco/records-management/issues/9  In addition I raised an (internal) ticket to investigate any issues preventing a new community release of AGS. This has not yet been prioritised over the enterprise work.

You mentioned that you have customised Share. Assuming this is with amps/jars then there is a project here to allow easily applying modules in a docker-compose environment: https://github.com/Alfresco/alfresco-docker-installer  In particular see the section in the README entitled "Deploying additional addons."

I am still hopeful that we will have a new community release next year though. This is something that comes up frequently within the team, and we believe that once we've made the first new release then we'll be able to resume regular releases.

**Comment by AdemOch** [comment]
@tpage-alfresco thank you for replying, besides these problems even when I try to follow the instructions just to try to install this version I face errors when I run the commands from their respective folders :
mvn clean install -Pstart-repo  : [ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.1:copy (fetch-share-services-amp) on project alfresco-governance-services-community-repo: Unable to find/resolve artifact.: Failed to read artifact descriptor for org.alfresco:alfresco-governance-services-community-rest-api-explorer:war:3.5.0-SNAPSHOT: Could not transfer artifact org.alfresco:alfresco-governance-services-community-rest-api-explorer:pom:3.5.0-SNAPSHOT from/to alfresco-internal (https://artifacts.alfresco.com/nexus/content/groups/private): Authentication failed for https://artifacts.alfresco.com/nexus/content/groups/private/org/alfresco/alfresco-governance-services-community-rest-api-explorer/3.5.0-SNAPSHOT/alfresco-governance-services-community-rest-api-explorer-3.5.0-SNAPSHOT.pom 401 Unauthorized -
mvn clean install -Pstart-share : [ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.1.0:jar (attach-javadocs) on project alfresco-governance-services-community-share: MavenReportException: Error while generating Javadoc: Unable to find javadoc command: The environment variable JAVA_HOME is not correctly set.

PS:running this on windows 10
thank you @tpage-alfresco  I really appreciate your help

**Comment by tpage-alfresco** [comment]
You will not have access to alfresco-internal, so that's why you're seeing the authentication failure. However you should be able to build the API explorer so that it's in your local .m2 directory.  Can you try `mvn clean install -DskipTests` from the rm-community directory?  Once everything is build locally then you could try `start-share` and `start-repo` again.

You could check JAVA_HOME is set correctly with `mvn --version`.  For AGS 3.5 then you need to use Java 11.

**Comment by tpage-alfresco** [comment]
Closing this due as I assume it has been resolved. Please feel free to reopen if you have further questions.
