### ISSUE TITLE
Where is 3.1 or is 3.0 compatible with ACS 6.1?

### ISSUE THREAD

**Issue by jpotts** [Alfresco/records-management#9]
In Enterprise Edition, ACS 6.1 requires 3.1, if I recall correctly.

ACS 6.1 has been in Community Edition for a while now. Is AGS 3.0.a compatible with 6.1?

If not, when will a version of Records Management Community be released that will work with the latest community release of ACS?

**Comment by rodicasutu** [comment]
The main reason there is no AGS 3.1.a is that the latest ACS community for 6.1 (6.1.2. ga) has an issue [ RM-6710](https://issues.alfresco.com/jira/browse/) that affects the AGS functionality. The issue was fixed but not included in an official ACS 6.1 community release.

**Comment by jpotts** [comment]
Is there a plan for resolving that?

**Comment by jiball** [comment]
@jpotts this requires a fix in ACS. The next community version of ACS 6.1 will have the fix applied and at this point we will release a compatible community version of AGS (AGS 3.1a)
The next ACS 6.1 community release is not currently scheduled until early 2020.

**Comment by maxodoble** [comment]
Meanwhile ACS 6.2 community is officially released for some time now....

So, are there **still** no plans for a RM release compatible to ACS 6.2.0GA?

**Comment by tpage-alfresco** [comment]
The latest statement I heard on a community ACS release was "We're looking to deliver something by October."  I checked up on it for the tech talk live presentation a few weeks back.

**Comment by mmrvelj** [comment]
It is October now, does anybody has any news?

**Comment by tpage-alfresco** [comment]
We have now released AGS 3.5.a which is compatible with ACS 7.0.  We have also given a Tech Talk Live presentation about this latest release:
* Recording: https://www.alfresco.com/events/webinars/tech-talk-live-129
* Q&A post: https://hub.alfresco.com/t5/events-meetups/tech-talk-live-129-q-amp-a/m-p/306849

There are currently no plans to make a release of AGS which is compatible with older versions of ACS (e.g. 6.1/6.2).

We are keen to avoid repeating a period of incompatibility though, and have moved the latest AGS code to live alongside the Repo and Share code:
* Latest AGS Community Repo: https://github.com/Alfresco/alfresco-community-repo/tree/master/amps/ags
* Latest AGS Community Share: https://github.com/Alfresco/alfresco-community-share/tree/master/amps/ags

As discussed in the TTL we are now testing compatibility between ACS and AGS in every commit on master and will be making releases of AGS at the same time (and with the same version number) as ACS. The next release of AGS will be Alfresco Community 7.1 (and the next enterprise release of AGS will be 7.1.0).
